name: Scheduled Action
on:
  schedule:     
    - cron: '0 11 * * 5'

jobs:
  Presentation:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is my pipeline ${{ github.actor }} 🎉"
  Branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is my branch ${{ github.ref }} 🔎"
  Files:
      runs-on: ubuntu-latest
      steps:
      - run: echo "These are my files"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
